on:
  push:
    branch:
     - main

jobs:
  build:
    name: build app
    runs-on: ubuntu-latest
    steps:
      - name: menampilkan teks
        run: echo "testing step build"
  test:
    name: test app
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: menampilkan teks
        run: echo "testing step test"
  deployment:
    name: deploy app
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: menampilkan teks
        run: echo "testing step deployment"- 
      - name : execute remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: /
            sudo rm -rf /var/www/html/*
            sudo git clone https://github.com/alvinsenjaya/HeroBiz /var/www/html
            
              
